### ISSUE TITLE
OPC UA LDS 1.03.367 Setup creates unneeded folders

### ISSUE THREAD

**Issue by RonnyLie** [OPCFoundation/UA-LDS#15]
The folder structure created by the LDS setup is still not consistent.

Obsolete XML-Configuration file was removed now, but the folder is still created
\ProgramData\OPC Foundation\Config

The folder of the former PKI structure of LDS 1.02 ist still created, but not used
\ProgramData\OPC Foundation\UA\Discovery\pki\trusted\certs

The new PKI folder of LDS 1.03 is located here \ProgramData\OPC Foundation\UA\pki
Wouldn’t it be better to stay compatible with LDS 1.02 and use the former PKI structure?
If the new setup 1.03 is run over a former 1.02 installation, the old settings and PKI folder is reused.
Is there an important reason to install PKI to a different location when installing on a clean system?

**Comment by erhardgrishaber** [comment]
1) The obsolete folder will be removed in the next release.

2) PKI folder: This was changed (in LDS v1.03) because it was not compatible with OPC UA Spec v1.03.
In LDS v1.02 the PKI folder structure was in „\ProgramData\OPC Foundation\UA\Discovery\pki\”
while the specifications sais it should be in „\ProgramData\OPC Foundation\UA\pki\”
The old folder structure is kept because of backward compatibility.

**Comment by erhardgrishaber** [comment]
The xml file will be kept because other applications might use it, so the folder will not be obsolete.
Fixed in LDS v.1.03.370
