### ISSUE TITLE
Could not verify certificate in old edited certificate store Error

### ISSUE THREAD

**Issue by kchtun** [OPCFoundation/UA-LDS#46]
My OPC UA Server cannot be registered in the LDS and the following message is written "Could not verify certificate in old defaut certificate store (0x801a0000)"is written in the LDS log file.

Can anyone help me ?

**Comment by erhardgrishaber** [comment]
Please provide the LDS version number.

**Comment by erhardgrishaber** [comment]
The error code means "BadCertificateUntrusted". Since the OPC-UA Server can use ony secured comunication, the certificates must be trusted. Copy the certificate of youre OPC-UA Server to  %CommonApplicationData%\OPC Foundation\UA\pki\trusted\certs. In Windows7 this translated to "C:\ProgramData\OPC Foundation\UA\pki\trusted\certs". At some point the certificate paths have changed in the LDS, so it is also trying to look in the old paths (usually it was in "C:\ProgramData\OPC Foundation\UA\Discovery\pki\trusted\cert"); the meeing of the message is that it did not find the certificate in the old paths either.

**Comment by JochenKalmbach** [comment]
If the server runs on the same computer, you can also set "AllowLocalRegistration = yes" in the ualds.ini file. Then automatically all servers are trusted by the LDS on the same computer.
See comments in the ini file:
```ini
# AllowLocalRegistration: (default=no) this will disable certificate trust checks for connections comming from
# localhost. Note that this is a security risk. Only enable this feature if you are aware of the full implications.
AllowLocalRegistration = yes
```
