### ISSUE TITLE
The LDS contains two PKI stores and two config files which can confuse the end user 

### ISSUE THREAD

**Issue by jenskiv** [OPCFoundation/UA-LDS#58]
It seems that through some historical reason the LDS contains two config files and pki stores. On a Windows system shows the config file C:\ProgramData\OPC Foundation\Config\Opc.Ua.DiscoveryServer.Config.xml to the pki store C:\ProgramData\OPC Foundation\UA\Discovery\pki.
The second config file C:\ProgramData\OPC Foundation\UA\Discovery\ualds.ini shows to C:\ProgramData\OPC Foundation\UA\pki. 
This behavior is confusing for the end user. It can be happen that the end user are using the wrong pki store.

**Comment by erhardgrishaber** [comment]
@jenskiv 
Here are some explanations regarding the issue:
1)	Two certificate (PKI) folders. This is due to backward compatibility. Some older applications have the older PKI folder hardcoded. Because of this we look in the old PKI folder and the new PKI folder for trusted certificates. This will probably not change for a while.
2)	Two configuration files: The LDS is using only one config file (ualds.ini), but the installer is deploying also a file Opc.Ua.DiscoveryServer.Config.xml. This is not used at all and not maintained (probably from very early releases of the LDS). 

If you have suggestions on how to improve the software, please write in a comment below.
Thank you.

**Comment by erhardgrishaber** [comment]
@jenskiv 
1. The two PKI folders will remain for backward compatibility with older applications.
2. The "xml" config file will be removed from the installer. The "ini" file is the only one used.
This will be available in the upcoming LDS release.

**Comment by erhardgrishaber** [comment]
The new LDS-ME version will be 1.04.402

**Comment by HunterDG** [comment]
Been pulling my hair out for several days trying to figure out where certs _should_ be.  The suggestion that this is related to differing confg.xml/ualds.ini files may be somewhat misleading.  My instance of ualds.ini **itself** references two different pki roots (ua\pki and ua\discovery\pki). 

I have different certificates (including rejected) in different pki roots, haven't figured out why yet.

which location is "new" for LDS v1.03?  

Why doesn't LDS use the "normal" %ProgramData%\OPC Foundation\CertificateStores\?

ualds.ini references:
CertificateStorePath = C:\ProgramData\OPC Foundation\\**UA\pki**\  <<< This is the problem??
CertificateFile = C:\ProgramData\OPC Foundation\\**UA\Discovery\pki**\own\ualdscert.der
CertificateFile = C:\ProgramData\OPC Foundation\UA\Discovery\pki\own\ualdscert.der
CertificateKeyFile = C:\ProgramData\OPC Foundation\UA\Discovery\pki\own\ualdskey.nopass.pem
CRLPath = C:\ProgramData\OPC Foundation\UA\Discovery\pki\crl
TrustListPath = C:\ProgramData\OPC Foundation\UA\Discovery\pki\trusted\certs
IssuerPath = C:\ProgramData\OPC Foundation\UA\Discovery\pki\issuer
RejectedPath = C:\ProgramData\OPC Foundation\UA\Discovery\pki\rejected
CertificateChainFile = C:\ProgramData\OPC Foundation\UA\Discovery\pki\own\cacert.pem

LDS checks/generates self-signed certs during startup at discovery\pki\own
Further, **OPC Config tool** expects certs and private keys to be under their respective folder (discovery\pki\own\\**certs** and discovery\pki\own\\**private**), but LDS places both at pki\\**own**


> @jenskiv
> 
> 1. The two PKI folders will remain for backward compatibility with older applications.
> 2. The "xml" config file will be removed from the installer. The "ini" file is the only one used.
>    This will be available in the upcoming LDS release.

But OPC Config tool uses config.xml? 
In fact, with default install of OPC Config tool, certs for LDS cannot be trusted/configured with OPC Config tool (Error: [Opc.Ua.DiscoveryServer does not have a trust list defined.](https://esupport.aspentech.com/servlet/rtaImage?eid=ka04P000000f6m2&feoid=00N4P00000Euu4A&refid=0EM4P000000b18J)) because the location of the config.xml file is not referenced in Opc.Ua.DiscoveryServer.xml.  After manually pointing Config tool to config.xml, LDS cert trusts can be managed. 

maybe this is all by design for compatibility but worth documenting anyway.

**Comment by erhardgrishaber** [comment]
@HunterDG: In older LDS releases there was a misunderstanding about where the certificates should be stored, due to changes in the specification.
In OPC-UA Spec v1.04 Part 12, it is written: "The certificates stores used by the LocalDiscoveryServer shall be organized as described in F.1. The root of the certificates stores shall be in the following location:
%CommonApplicationData%\OPC Foundation\UA\pki". So this is the default location used by the latest LDS version. The older location "...\Discovery\pki" is kept for backwards compatibility. 
The LDS can not maintain multiple configuration files (like *.xml); the "ualds.ini" is the only one (At least for the last 7 years).
I would suggest to update the LDS to latest version (recommended anyway, due to bug fixes). If possible, I would suggest to remove the existing "ualds.ini" as it contains many "old paths"; a new file will be generated at restart.
Please use LDS v1.04.402

**Comment by HunterDG** [comment]
Thanks for the info!  The spec is the spec!

From end-user perspective, would be nice if UA Config Tool transparently handled the LDS cert edge-case, but perhaps this isn't something most folks run into anyway.  

Much appreciated.
