### ISSUE TITLE
UA-LDS does not send back SRV&TXT mdns messages [QUESTION]

### ISSUE THREAD

**Issue by STUBA-rupr** [OPCFoundation/UA-LDS#59]
## Motivation
For a use case when LDS's url is not well-known (embedded devices) a multicast discovery is an mechanism which can discover url of LDS.
## Observation
I observed that LDS can be identified only in case when LDS has started while multicast server was already running. Otherwise multicast server cannot recognize it.
**LDS:**
![image](https://user-images.githubusercontent.com/55546830/73824946-5cf2c980-47fb-11ea-935b-7a1925b2a984.png)
**mdns server:**
![image](https://user-images.githubusercontent.com/55546830/73824961-6845f500-47fb-11ea-9b0c-52275fcc0328.png)
## Example from open62541
**LDS:**
![image](https://user-images.githubusercontent.com/55546830/73825244-eb674b00-47fb-11ea-97fe-dfa959140b2b.png)
**mdns server:**
![image](https://user-images.githubusercontent.com/55546830/73825260-f1f5c280-47fb-11ea-84d3-881798007022.png)
## Question
How could I achieve, what mdns messages I should consider discover OPC Foundation LDS on network? 
I saw that OPC Foundation LDS running on two different servers can recognize them.

**Comment by erhardgrishaber** [comment]
1. The purpose of the LDS is for local Servers to register and local Clients to query results. This means that the LDS's url should be always be knows as "localhost" with the default port 4840. Anything else might be a misuse.
2. At startup the LDS is :
	- registering itself (and all known OPC-UA Servers) manually to a mdns server and automatically in a defined periodic interval (usually 5 seconds). See DNSServiceRegister.
	- starts listening for mdns notifications (from a mdsn server) in a defined periodic interval (usually 5 seconds). See DNSServiceBrowse and DNSServiceResolve.
	Tested with Bonjour & Avahi.
3. At shutdown the LDS is:
	- unregistering itself (and all known OPC-UA Servers) from a mdns server.
	- stops listening for mdsn notifications.

In order to identify the LDS from mdns messages, it is necessary for the mdsn server and the LDS to run at the same time. It not possible to "find" the LDS if it is not running because it is registering at startup and unregistering at shutdown.

To specifically identify an LDS (from other OPC-UA Servers) while browsing/resolving from a mdns server, I recommend to look in the TXTRecord for "caps". The LDS is setting this to the value "LDS". "caps" comes from "capabilities" and "LDS" means that the Server is a Local Discovery Server.
