### ISSUE TITLE
UA Application folder not found in MMC 

### ISSUE THREAD

**Issue by robotsGuy** [OPCFoundation/UA-LDS#69]
Hello, 

Lately, I've installed the Local Discovery Server (LDS) from OPCFoundation website and i've tried to register an OPC UA server in LDS but an error message shows up "The local Discovery Server doesn't have a self-signed certificate", in the MMC i didn't find a certificate for LDS and there's no UA Applications folder.

Thank you in advance,

**Comment by erhardgrishaber** [comment]
@robotsGuy: Who is giving this error message ? Where ? I checked the source code and the LDS is not giving such message.
I assume then it is the Server (that is trying to register).
The LDS is creating a self-sign certificate at startup (if non exists) at this location (in Windows10): C:\ProgramData\OPC Foundation\UA\pki\own\certs. Please check if it is there.
If there is a problem in loading the certificate, an error message should be visible in the log file: C:\ProgramData\OPC Foundation\UA\Discovery\ualds.log Please check if there is any entry.
Question1: What does "MMC" mean ?
Question2: What do you mean with "UA Application folder not found" ? What folders do you expect to have ?
Is the LDS service running ?
![image](https://user-images.githubusercontent.com/17177166/117119468-666a3900-ad92-11eb-8bae-658db612a0ae.png)
Please make sure that, since registering a Server to the LDS is secured-only, that the certificates are trusted on both ends; otherwise it will fail.

**Comment by robotsGuy** [comment]
Hello 

@erhardgrishaber  thank you for your feedback.
Yes a server is giving me this error ( ABB IRC5 OPC UA Server)
MMC : Microsoft Management Console
I found some methods to register an OPC server in LDS and UA Application folder should exist to do so. (as you can see un the url below)  
URL : http://documentation.unified-automation.com/uagateway/1.3.1/html/register_at_lds.html

Yes, the LDS service is running. 

Thanks,

**Comment by erhardgrishaber** [comment]
@robotsGuy The provided URL is describing hot to put the Server's certificate in the WindowsCetificateStore, so that the LDS can find it as a "trusted certificate" when the Server is trying to register. The "UA Applications" folder is not something the LDS is creating and has nothing to do with OPC-UA (it is not something the LDS can fix). In any case, the error message seems to be from the other end. The Server also need to trust the LDS (certificate). It is possible that the Server can not find the LDS certificate and that is why the registration fails. You probably need to ask the vendor of the Server (or debug yourself if possible) why this message is shown. As long as the LDS is running + has a valid certificate + it does not give any errors, there is not much that I can do (on the LDS part). What I can recommend is for you do manually exchange certificates. Copy the Server certificate to C:\ProgramData\OPC Foundation\UA\pki\trusted\certs + Copy the LDS certificate (C:\ProgramData\OPC Foundation\UA\pki\own\certs\ualdscert.der) in the "trusted certificates" folder of the Server (ABB IRC5 OPC UA Server)
